[WIP] NetworkQoS CRD
ovn-kubernetes/ovn-kubernetes pull request #4508
Opened 2024-07-08 22:42 UTC by flavio-fernandes

This is the CRD for Network QoS, based on the enhancement https://github.com/ovn-org/ovn-kubernetes/pull/4366

**Note**: Not to be merged before https://github.com/ovn-org/ovn-kubernetes/pull/4366 is approved.

2024-07-12 19:04 UTC, flavio-fernandes commented
known flake:  https://github.com/ovn-org/ovn-kubernetes/issues/4480

2024-07-18 19:24 UTC, tssurya commented
haha btw recently a controller pkg was added: https://github.com/ovn-org/ovn-kubernetes/tree/master/go-controller/pkg/controller to be reused everywhere.. not sure if its easy to port now but when I wrote ANP we didn't have it plus I wanted everything in same reconcile loop and not have multiple controllers for each object... but given we have no developer docs to mandate one must use controller package its upto the developer.. but wanted to bring it to your attention

2024-10-22 00:17 UTC, flavio-fernandes commented
Known flake:  https://github.com/ovn-org/ovn-kubernetes/issues/3986
https://github.com/ovn-org/ovn-kubernetes/actions/runs/11449422218/job/31855967593?pr=4508

2024-10-22 00:21 UTC, flavio-fernandes commented
@pperiyasamy @trozet @tssurya PTAL. We think this PR is ready for your blessings.

2024-12-18 15:26 UTC, flavio-fernandes commented
/assign @tssurya 
/assign @npinaeva

2024-12-18 16:58 UTC, flavio-fernandes commented
Known flake:   https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4670

```
Summarizing 7 Failures:
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when no EgressIPs are configured makes sure that the cluster is still operational (update kubelet first, the IP address later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when no EgressIPs are configured makes sure that the cluster is still operational (update the IP address first, kubelet later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when EgressIPs are configured makes sure that the EgressIP is still operational (update kubelet first, the IP address later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when EgressIPs are configured makes sure that the EgressIP is still operational (update the IP address first, kubelet later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when ETP=Local service with host network backend is configured makes sure that the flows are updated with new IP address (update kubelet first, the IP address later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when the node IPv4 address is updated [BeforeEach] when ETP=Local service with host network backend is configured makes sure that the flows are updated with new IP address (update the IP address first, kubelet later)
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:202
  [FAIL] Node IP and MAC address migration when when MAC address changes [BeforeEach] when a nodeport service is configured Ensures flows are updated when MAC address changes
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/node_ip_mac_migration.go:549
  ```

2025-02-11 23:31 UTC, flavio-fernandes commented
unit test failure is unrelated to this change:

```
2025-02-11T22:53:00.1195619Z ^[[38;5;9m^[[1mSummarizing 1 Failure:^[[0m
2025-02-11T22:53:00.1198926Z   ^[[38;5;9m[FAIL]^[[0m ^[[0mHybrid SDN Master Operations ^[[38;5;9m^[[1m[It] handles a HO node is switched to a OVN node^[[0m
2025-02-11T22:53:00.1200574Z   ^[[38;5;243m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/hybrid_test.go:1454^[[0m
2025-02-11T22:53:00.1201537Z
2025-02-11T22:53:00.1216355Z ^[[38;5;9m^[[1mRan 501 of 504 Specs in 648.949 seconds^[[0m
```

looks like flake  https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4387 :

```
2025-02-11T22:45:16.1516834Z   ^[[38;5;9m[FAILED] Timed out after 2.001s.
2025-02-11T22:45:16.1517286Z   Expected
2025-02-11T22:45:16.1518150Z       <[]*nbdb.LogicalRouterStaticRoute | len:2, cap:2>: [
2025-02-11T22:45:16.1518701Z           {
2025-02-11T22:45:16.1519366Z               UUID: "f746a447-5535-4c16-895e-42e4c82dd457",
2025-02-11T22:45:16.1519943Z               BFD: nil,
2025-02-11T22:45:16.1520427Z               ExternalIDs: {
2025-02-11T22:45:16.1521263Z                   "name": "hybrid-subnet-node1:node-windows",
2025-02-11T22:45:16.1521797Z               },
2025-02-11T22:45:16.1522314Z               IPPrefix: "10.1.3.0/24",
2025-02-11T22:45:16.1522877Z               Nexthop: "10.1.1.3",
2025-02-11T22:45:16.1523383Z               Options: nil,
2025-02-11T22:45:16.1523897Z               OutputPort: nil,
2025-02-11T22:45:16.1524371Z               Policy: nil,
2025-02-11T22:45:16.1524874Z               RouteTable: "",
2025-02-11T22:45:16.1525269Z           },
2025-02-11T22:45:16.1525582Z           {
2025-02-11T22:45:16.1526252Z               UUID: "ef005cfd-a18b-4a2b-b85b-b5591d57f637",
2025-02-11T22:45:16.1526825Z               BFD: nil,
2025-02-11T22:45:16.1527282Z               ExternalIDs: {
2025-02-11T22:45:16.1528034Z                   "name": "hybrid-subnet-node1-gr",
2025-02-11T22:45:16.1528518Z               },
2025-02-11T22:45:16.1529032Z               IPPrefix: "10.1.3.0/24",
2025-02-11T22:45:16.1529628Z               Nexthop: "100.64.0.1",
2025-02-11T22:45:16.1530156Z               Options: nil,
2025-02-11T22:45:16.1530669Z               OutputPort: nil,
2025-02-11T22:45:16.1531161Z               Policy: nil,
2025-02-11T22:45:16.1531646Z               RouteTable: "",
2025-02-11T22:45:16.1532029Z           },
2025-02-11T22:45:16.1532313Z       ]
2025-02-11T22:45:16.1532711Z   to have length 0^[[0m
2025-02-11T22:45:16.1534479Z   ^[[38;5;9mIn ^[[1m[It]^[[0m^[[38;5;9m at: ^[[1m/home/runner/work/ovn-kubernetes/ovn-kubernetes/go-controller/pkg/ovn/hybrid_test.go:1454^[[0m ^[[38;5;243m@ 02/11/25 22:45:16.134^[[0m
```

2025-02-18 18:21 UTC, flavio-fernandes commented
Known Flakes:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4348
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936

2025-02-19 17:27 UTC, flavio-fernandes commented
Known Flakes:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4806
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4829

2025-02-24 20:48 UTC, flavio-fernandes commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	NetworkAttachmentRefs []corev1.ObjectReference `json:"netAttachRefs,omitempty"`
.

2025-02-24 22:46 UTC, trozet requested changes
made it up to add e2e tests for networkqos

will finish tmrw

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_controller.go
> +	klog.V(4).Infof("Adding Network QoS %s", key)
as we scale up number of controllers (UDNs/NADs) wont this print that many times?

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_controller.go
> +	klog.V(5).Infof("Adding Namespace in Network QoS controller %s", key)
why is this one 5, but the nqos ones are 4

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_namespace.go
> +			continue
if classifier is nil, that means it covers all traffic, so in that case we have no address set?

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_node.go
> +				c.nqosNamespaceQueue.AddAfter(key, 3*time.Second)
why does it queue after 3 seconds? this seems like it could become a race. Did you copy this from ANP or something? I think it would be better to queue nQOS keys in other handlers, and then do everything in that thread.

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_node.go
> +				klog.Warningf("NetworkQoS not synced yet: %s", nqosKey)
why do you only queue it if it doesn't already exist in the cache?

2025-02-24 22:46 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos_pod.go
> +	// We don't want to shortcuit only local zone pods here since peer pods
nit shortcut

2025-02-25 15:11 UTC, jcaamano commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		nadKey := joinMetaNamespaceAndName(nadRef.Namespace, nadRef.Name)
Yup, that's done in the BGP UDN PR under review:
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4929/commits/468ee025185654b0bb3071d89cda910881474161

2025-02-28 20:44 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	klog.V(5).Infof("%s - Processing NetworkQoS %s/%s", c.controllerName, nqos.Namespace, nqos.Name)
the check is done at line 74, maybe it's not obvious because it's in the "else" block.

2025-02-28 21:58 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +			return nil
it's considered non-retriable for this situation, returning error will trigger retry.
we will just it as mark error and leave it there, until the selectors are fix, which will trigger a new event.

2025-02-28 22:00 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +				c.updateNQOSStatusToNotReady(nqos.Namespace, nqos.Name, "specifying both ipBlock and podSelector/namespaceSelector is not allowed", nil)
agreed, will update.

2025-02-28 23:20 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		klog.V(5).Infof("%s - NetworkQoS %s has gone", c.controllerName, key)
is it ok to change it to 6? it could be helpful in troubleshooting/debugging.

2025-02-28 23:21 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		klog.V(6).Infof("Net-attach-def %s is not managed by controller %s ", nadKey, c.controllerName)
ack, removing this.

2025-02-28 23:31 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +				return fmt.Errorf("invalid protocol: %s, valid values are: tcp, udp, sctp", ruleSpec.Classifier.Port.Protocol)
changing to uppercase.

2025-03-01 04:13 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +// matching pod or namespace changes.
added comment.

2025-03-01 04:47 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		return fmt.Errorf("NetworkQoS %s/%s reconciled successfully but unable to patch status: %v", nqos.Namespace, nqos.Name, e)
fixed.

2025-03-01 04:57 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	utilruntime.HandleError(fmt.Errorf("%v failed with: %v", nqosKey, err))
added controller name

2025-03-01 05:10 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +// uses externalIDs to figure out ownership
added comment.

2025-03-01 05:23 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	klog.V(5).Infof("Patched the status of NetworkQoS %s/%s with condition type %v/%v",
ack.

2025-03-01 05:37 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		klog.Warningf("Failed to update the status of NetworkQoS %s/%s, err: %v", namespace, name, err)
added.

2025-03-01 05:38 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_pod.go
> +// setPodForNQOS wil lcheck if the pod meets source selector or dest selector
fixed

2025-03-01 05:44 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		if err := c.setPodForNQOS(pod, nqosState, ns); err != nil {
check is done within the function by calling getPodAddresses, will skip the operation if address is empty.

2025-03-01 05:47 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_controller.go
> +	klog.V(4).Infof("Adding Network QoS %s", key)
removed this.

2025-03-01 05:48 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_controller.go
> +	klog.V(5).Infof("Adding Namespace in Network QoS controller %s", key)
removed.

2025-03-01 05:49 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_namespace.go
> +			continue
yes.

2025-03-01 05:51 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_pod.go
> +	// We don't want to shortcuit only local zone pods here since peer pods
fixed.

2025-03-01 06:16 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_node.go
> +				c.nqosNamespaceQueue.AddAfter(key, 3*time.Second)
the situation here is that the NetworkQoS may not get reconciled yet, so line 82 adds the key to trigger a sync for it. if we requeue namespace key here immediately, namespace handler probably still won't be able to see NetworkQoS in cache, so want to add 3 seconds delay so that NetworkQoS handler will have time to process it.

2025-03-01 06:20 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_node.go
> +				klog.Warningf("NetworkQoS not synced yet: %s", nqosKey)
just want to make sure the NetworkQoS get reconciled, in case it's out of sync for some reason.

2025-03-01 15:43 UTC, flavio-fernandes commented
Hello @trozet 

@jxiaobin made changes based on your [awesome] review, and I merged them into this PR. Thank you so much! I wasn’t sure if you preferred having the changes as a separate commit, so you can easily see the deltas, or if you’d rather have them squash-merged with the pre-existing commits. Maybe both?

What I mean is, if you’re okay with the changes in commit [a7eff238a7708fafb025701703f35c268dbb23a4](https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4508/commits/a7eff238a7708fafb025701703f35c268dbb23a4), let me know, and I will rebase and squash them into 9053e0d09120dbc7432a57016e6f060af96547a8.

Just let me know, please!

2025-03-03 19:36 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +				c.updateNQOSStatusToNotReady(nqos.Namespace, nqos.Name, "specifying both ipBlock and podSelector/namespaceSelector is not allowed", nil)
There is also CEL in CRD spec, but we think adding code here would provide more clarity.

2025-03-11 20:09 UTC, jxiaobin commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	NetworkAttachmentRefs []corev1.ObjectReference `json:"netAttachRefs,omitempty"`
agreed.

2025-03-13 00:12 UTC, flavio-fernandes commented
Known flake:  https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4139
```
[FAIL] External Gateway With Admin Policy Based External Route CRs BFD e2e multiple external gateway validation Should validate TCP/UDP connectivity to multiple external gateways for a UDP / TCP scenario [It] IPV6 tcp
```

2025-03-13 15:46 UTC, flavio-fernandes commented
/retest-failed

2025-03-13 16:04 UTC, flavio-fernandes commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	// +kubebuilder:validation:MaxItems=20
.

2025-03-13 16:04 UTC, flavio-fernandes commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	// egress a collection of Egress NetworkQoS rule objects. A total of 20 rules will
fixed
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4508/commits/cc95290c8229445d11a1dadccc361b87d0bf4a4f#r1993851852

2025-03-13 16:07 UTC, flavio-fernandes commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	// determined by the order in which the rule is written. Thus, a rule that appears
@trozet :  @npinaeva did a great job going over this topic in the review of the enhancement: https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4366#discussion_r1923389552   This is how it is implemented in this pr.

2025-03-13 16:08 UTC, flavio-fernandes commented
hi @trozet ! I have rebased this pr, but kept the deltas as distinct commits so you do not need to guess what changed after your latest review. PTAL.

2025-03-17 17:14 UTC, flavio-fernandes commented on go-controller/pkg/clustermanager/status_manager/status_manager_test.go
> +			NetworkSelector: metav1.LabelSelector{
.

2025-03-18 16:14 UTC, girishmg commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	// egress a collection of Egress NetworkQoS rule objects. A total of 20 rules will
@trozet the QoS priority maps to OVN QoS Priority using this math:

10000 + NetworkQoS.priority * 20 + index(rule)

So, we needed some constant to do the above math and 20 deemed good enough number of rules for a given QoS object. 

The users can always create more QoS objects if they run out of rules.

2025-03-18 16:18 UTC, girishmg commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	// egress a collection of Egress NetworkQoS rule objects. A total of 20 rules will
if we think `20` is less and we want more room to grow, we can change this to 50.

2025-03-18 16:24 UTC, girishmg commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	NetworkAttachmentRefs []corev1.ObjectReference `json:"netAttachRefs,omitempty"`
> .is QoS applied to both of its interfaces?

yes, it will be applied to both of these interfaces for the traffic matching the rules per the `to` object. 

Say, the `to` object has namespaceSelector/podSelector populated and it selects a Pod.. that pod should have interfaces in same NAD.. otherwise, no marking will happen.

```
FIELD: to <[]Object>

DESCRIPTION:
    Destination describes a peer to apply NetworkQoS configuration for the
    outgoing traffic.
    Only certain combinations of fields are allowed.
    
FIELDS:
  ipBlock	<Object>
    cidr	<string> -required-
    except	<[]string>
  namespaceSelector	<Object>
    matchExpressions	<[]Object>
      key	<string> -required-
      operator	<string> -required-
      values	<[]string>
    matchLabels	<map[string]string>
  podSelector	<Object>
    matchExpressions	<[]Object>
      key	<string> -required-
      operator	<string> -required-
      values	<[]string>
    matchLabels	<map[string]string>    
```

2025-03-18 16:26 UTC, girishmg commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		if bwBurst > 0 {
I agree. We will address this in the subsequent PR.

Ideally, I have sen BurstSize to be double the PacketRate.

2025-03-20 17:39 UTC, flavio-fernandes commented
Flake:  https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936

```
[FAIL] e2e egress IP validation Network Segmentation: IPv4 L2 role primary [OVN network] Using different methods to disable a node's availability for egress Should validate the egress IP functionality against remote hosts [It] disabling egress nodes impeding GRCP health check
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/egressip.go:479
```

2025-03-21 18:29 UTC, flavio-fernandes commented on go-controller/pkg/crd/networkqos/v1/types.go
> +	Port Port `json:"port"`
@trozet: Added the support for multiple ports here:  https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4508/commits/5c2761c009d1ec3ab0e0be961aaca601ca66b26e
TY @jxiaobin !

2025-04-09 18:28 UTC, flavio-fernandes commented
Flake:  https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5170

```
  [FAIL] [sig-network] Services [It] should respect internalTrafficPolicy=Local Pod and Node, to Pod (hostNetwork: true) [sig-network]
  k8s.io/kubernetes/test/e2e/network/service.go:2696
  [FAIL] [sig-network] Services [It] should respect internalTrafficPolicy=Local Pod (hostNetwork: true) to Pod [sig-network]
  k8s.io/kubernetes/test/e2e/network/service.go:2594
  ```

2025-04-12 02:53 UTC, flavio-fernandes commented
Flake  https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5170 :

```
Summarizing 2 Failures:
  [FAIL] [sig-network] Services [It] should respect internalTrafficPolicy=Local Pod and Node, to Pod (hostNetwork: true) [sig-network]
  k8s.io/kubernetes/test/e2e/network/service.go:2696
  [FAIL] [sig-network] Services [It] should respect internalTrafficPolicy=Local Pod (hostNetwork: true) to Pod [sig-network]
  k8s.io/kubernetes/test/e2e/network/service.go:2594
```

2025-04-14 21:03 UTC, trozet requested changes
So my only major issue left with this PR is the resource handling between types. We have handlers for:

1. nqos - runs setPodForNQOS on all pods (setPodForNQOS), updates cache with stored qos info
2. namespace - loops all nqos in cache, processes all pods in namespace for destination address set only
3. pod - loops all nqos, runs setPodForNQOS on pod
4. node - loops all nqos, runs setPodForNQOS for pods on node

Each of these tries to serialize behavior through locking the cache key for network qos. However, I think there can still be races due to lag in the arrival of events on different informers. IMHO I think you should change the handling so that:

1. nqos - handles all OVN related configuration, essentially detects what needs to be updated and runs setPodForNQOS
2. namespace - determines if its namespace is selected by an nqos, queues nqos key onto nqosQueue
3. pod - determines if its pod is selected by an nqos, queues nqos key onto nqosQueue
4. node - do we actually need this? the pod event will on the new node will trigger handling

The reason I suggest this is because we have had faced issues with similar designs in the past. After a lot of work we decided the above approach is the cleanest. Trying to debug across multiple resource handler threads is challenging, and if we can reduce to one it makes things much easier to follow and eliminates race conditions. For an example, take a look at controller -> apbroute. In there we watch pods, and namespaces, they requeue keys for policies. Then all the real configuration is done in the policy handler.


I would also suggest decoupling addQoSToLogicalSwitch from configureSourcePod and just configure it during ensureNetworkQos. I would apply it to all nodes that are in my zone, and not scope per pod.

2025-04-16 14:18 UTC, martinkennelly commented on test/e2e/networkqos.go
> +		podImage       = "nicolaka/netshoot"
should be the "fqdn" of the image - docker.io/ or whatever

2025-04-17 19:32 UTC, flavio-fernandes commented on test/e2e/networkqos.go
> +		podImage       = "nicolaka/netshoot"
good point! we should actually use the image in github.

2025-04-24 23:21 UTC, flavio-fernandes commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		switch networkSelector.NetworkSelectionType {
heh, for now, yes. Just like the additional bw attrs, lets defer udn so we can merge this long lived pr, please.

2025-04-25 12:23 UTC, flavio-fernandes commented
Flakes:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5170
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4139

2025-04-26 06:58 UTC, jxiaobin commented on docs/okeps/okep-4380-network-qos.md
> +	// networkSelector selects the networks on which the pod IPs need to be added to the source address set.
yes, as @flavio-fernandes mentioned in the previous comment, we added a new CEL validation rule to address this.

2025-04-26 06:59 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos_node.go
> +	pods, err := c.getPodsByNode(node.Name)
this has been removed in the latest commit.

2025-04-26 07:20 UTC, jxiaobin commented
@trozet we refactored the event handlers as you suggested, plz take a look. 
the node handler only responds node zone change event, which would trigger networkqos controller to remove qos from old zone while add it to the new zone, I assume this is a valid case?

2025-04-27 13:30 UTC, flavio-fernandes commented
Only test failure is the known issue with `should respect internalTrafficPolicy=Local Pod` : https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5170#issuecomment-2832442487

2025-04-28 01:29 UTC, flavio-fernandes commented
Flakes:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936
- should respect internalTrafficPolicy=Local Pod : https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5170#issuecomment-2832442487

2025-04-30 13:07 UTC, trozet requested changes
so this is closer, but need to change how we enqueue objects

2025-04-30 13:07 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	nqos, quit := c.nqosQueue.Get()
we want to keep the queues using keys, and then in here once you lock the key, you will list the nqos from the informer cache and try to sync it. Otherwise by queuing nqos events from other handlers, you can essentially modify the real order of events as those handlers are asynchronous, and we can end up with incorrect configuration. Take a look at:

https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/ovn/controller/apbroute/external_controller_policy.go#L40

2025-04-30 13:07 UTC, trozet commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		if err := c.ensureNetworkQos(nqos); err != nil {
when you sync network qos, you are going to go through a lot of pods that are affected for everytime an nqos is reconciled, and if there is a podSelector matching a lot of pods; that will call setPodForNQOS ->  configureSourcePod -> AddAddresses. But with the model I suggested you use, what will happen is:

1. a single pod is added, triggers nqos pod handler to queue the nqos key onto the queue
2. nqos handler sees a new key, and processes it, triggering this update for all pods

I was worried this would result in an OVSDB txn for pods that already exist in the address set, but it looks like we are smart and if we have the address already in the addressset, we do not issue the txn:

```
func (as *ovnAddressSet) addAddresses(addresses []string) ([]ovsdb.Operation, error) {
	if len(addresses) == 0 {
		return nil, nil
	}

	uniqAddresses := getUniqueAddresses(addresses)

	if as.hasAddresses(uniqAddresses...) {           <-------------HERE
		return nil, nil
	}

	klog.V(5).Infof("(%s) adding Addresses (%s) to address set", asDetail(as), uniqAddresses)

	addrset := nbdb.AddressSet{
		UUID: as.uuid,
		Name: as.hashName,
	}
	ops, err := libovsdbops.AddAddressesToAddressSetOps(as.nbClient, nil, &addrset, uniqAddresses...)
	if err != nil {
		return nil, fmt.Errorf("failed to add addresses %v to address set %+v: %v", uniqAddresses, addrset, err)
	}

	return ops, nil
}
```

We also only add networkQoS to logical switch if it isnt in our switchRefs cache. So I think we are good on making sure we do not do unnecessary work on every nqos sync. Just wanted to call it out here in case we have performance questions later. Nothing you need to change.

2025-04-30 13:09 UTC, trozet commented
> @trozet we refactored the event handlers as you suggested, plz take a look. the node handler only responds node zone change event, which would trigger networkqos controller to remove qos from old zone while add it to the new zone, I assume this is a valid use case?

@flavio-fernandes I don' t think this is a valid use case once you are in IC. We do not move nodes in and out of zones, and we are dropping support for multiple nodes per zone. The only case I can see this for is maybe handling non-IC -> IC upgrade?

2025-04-30 16:37 UTC, flavio-fernandes commented
Flakes:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4474

2025-04-30 20:53 UTC, flavio-fernandes commented
@trozet wrt https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4508#discussion_r2068572144
```
	var selectedNads []*nadv1.NetworkAttachmentDefinition
	for _, networkSelector := range networkSelectors {
		switch networkSelector.NetworkSelectionType {
```
| what is the reason for that @flavio-fernandes ?

With the latest changes for network selector that Jaime did, we actually have a list instead of a single network selector.
The logic here visits all of them and puts together the NADs we need to use, collectively. Is that what you asked?

2025-04-30 21:47 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	nqos, quit := c.nqosQueue.Get()
ack, we've reverted to use string key.

2025-05-01 00:25 UTC, flavio-fernandes commented
Flake:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936

2025-05-01 14:05 UTC, flavio-fernandes commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +		switch networkSelector.NetworkSelectionType {
Update: Will be tracked under https://github.com/ovn-kubernetes/ovn-kubernetes/issues/5222
so we add support for UDN types as well.

2025-05-01 15:30 UTC, jxiaobin commented on go-controller/pkg/ovn/controller/network_qos/network_qos.go
> +	nqos, err := c.nqosLister.NetworkQoSes(nqosNamespace).Get(nqosName)
fixed.

2025-05-01 15:44 UTC, trozet approved these changes
/lgtm

will wait on CI

2025-05-01 22:00 UTC, flavio-fernandes commented
Flake: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4139
```
Summarizing 1 Failure:
  [FAIL] External Gateway With annotations BFD e2e non-vxlan external gateway through an annotated gateway pod Should validate TCP/UDP connectivity to an external gateway's loopback address via a pod with external gateway annotations enabled [It] TCP ipv6
  /home/runner/work/ovn-kubernetes/ovn-kubernetes/test/e2e/external_gateways.go:3257
  ```

2025-05-02 01:10 UTC, merged