[release-1.0]: Fix several issues for supporting DPUs
ovn-kubernetes/ovn-kubernetes pull request #4761
Opened 2024-10-08 07:06 UTC by EvenChang

**What this PR does and why is it needed**

(cherry picked from PR https://github.com/ovn-org/ovn-kubernetes/pull/4634)

2024-10-08 07:11 UTC, EvenChang commented on helm/ovn-kubernetes/values.yaml
> +    tag: master
I have a question.
Do we need to change the tag from master to release-1.0?

2024-12-23 21:59 UTC, crnithya commented
Hello @EvenChang the changes look good to me. And can you please rebase to the latest?

2024-12-26 02:00 UTC, EvenChang commented
> Hello @EvenChang the changes look good to me. And can you please rebase to the latest?

Sure, If I finished it I will let you know!

2025-01-07 12:49 UTC, flavio-fernandes commented on helm/ovn-kubernetes/values.yaml
> +    tag: master
Not necessarily. These are just the defaults. Also, 'ovn-org' is now 'ovn-kubernetes' with the move to the new repository. Not sure about changing that, since release-1.0 predates that.

2025-01-07 12:50 UTC, flavio-fernandes commented
hi @EvenChang . Could you pull in the commits in https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4941 into this PR? I think they are needed here too.

2025-01-08 01:11 UTC, EvenChang commented
> hi @EvenChang . Could you pull in the commits in #4941 into this PR? I think they are needed here too.

No problem!  Could you please take a look ? I've merged #4941 into this PR.

2025-01-08 03:20 UTC, girishmg approved these changes

2025-01-08 03:25 UTC, girishmg commented
@EvenChang looks like there are issues with DCO (some of the commits is not properly signed off)

@flavio-fernandes various lanes in the CI failed, can you please check?

2025-01-08 03:25 UTC, girishmg requested changes
Various checks have failed, please fix them.

2025-01-10 16:55 UTC, flavio-fernandes commented
hi @EvenChang . Could you pull in the commits of the latest https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4941 into this PR? I think they are needed here too. They include fixes for the build issue you are having. Sorry for asking you to do this again.

2025-01-13 16:32 UTC, flavio-fernandes commented
hi @EvenChang. Please rebase once again to pick up the latest cicd fixes.

2025-01-14 05:48 UTC, EvenChang commented
> hi @EvenChang. Please rebase once again to pick up the latest cicd fixes.

Hi @flavio-fernandes 
Sorry for the late response. 
I've rebased to the latest release-1.0, but there are still a few failures. 
Could you please take a look? If there's anything I can help with, please let me know. 
Thanks!

2025-01-21 21:27 UTC, crnithya commented
Hi @EvenChang can you please backport https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4974 Thank you.

2025-01-21 21:28 UTC, flavio-fernandes requested changes
hi @EvenChang. Making progress! ;) Please pull in missing commits that are still missing in this pr in order to make dpu work.
/cc @crnithya   @cathy-zhou

2025-01-21 21:34 UTC, cathy-zhou commented
@crnithya this also need your changes in MR https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4974, right?

2025-01-21 21:40 UTC, crnithya commented
@cathy-zhou yes, https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4974 is needed and I just mentioned it few minutes back.

2025-01-22 05:24 UTC, EvenChang commented
Hi @crnithya,
I've merged #4974 into this PR
But there's still a test failure. Could you please take a look? Thanks!

2025-01-22 15:52 UTC, flavio-fernandes commented
Known flake: https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4289

2025-01-22 15:54 UTC, flavio-fernandes approved these changes
/lgtm

2025-01-22 23:27 UTC, crnithya commented
Thanks @EvenChang. LGTM

2025-01-23 01:06 UTC, EvenChang commented
No problem!  Thanks for everyone's help!

2025-01-23 22:33 UTC, girishmg approved these changes

2025-01-23 22:33 UTC, merged