Import learnt BGP routes into OVN
ovn-kubernetes/ovn-kubernetes pull request #4835
Opened 2024-11-13 16:52 UTC by jcaamano

This commit adds a new controller to import BGP learnt routes into OVN.

The controller runs in ovnkube-controller so it only supports IC
architecture where ovnkube-controller has kernel access on each node.

Networks should register to this controller to have routes imported for
them. Routes are imported into the network's gateway router. Multipath
routes are supported.

The controller subscribes for netlink route events. When a route is
updated, the corresponding network is queued to be sync'ed. A network is
also sync'ed when registered to the controller.

Synchronizations are delayed by a small amount of time to prevent a
series of consecutive route updates so synchornize the same network
twice. Synchronizations apply the difference between current and desired
state.

The controller subscribes to netlink link events to learn the routing
table associated to a network vrf. The network is inferred from the vrf
device name. When learning the routing table, the corresponding network
is queued to be sync'ed.

Currently based on top of https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4691

2025-01-06 23:18 UTC, trozet requested changes

2025-01-06 23:18 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +					continue
so timer goes off and we are still subscribed, then we dont restart the timer? What happens if right after this we are unsubscribed and dont get any more events, now we never resubscribe?

2025-01-06 23:18 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	setTimer := func(t *time.Timer, d time.Duration) *time.Timer {
how is this better than the methods we use in other controllers wehre we just use a ticker and every so often we check to make sure we are subscribed?

2025-01-06 23:18 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +		t := setTimer(nil, subscribePeriod)
if we stop we need to in this goroutine we need to stop the timer to avoid leak. In go 1.23 we dont have to but we are still on 1.22 I think:

https://pkg.go.dev/time#NewTimer

2025-01-06 23:18 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	reconcile := info != nil && table != 0 && !current
nit: s/reconcile/needsReconcile

2025-01-06 23:18 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	reconcile := info != nil && table != 0 && !current
it looks like you are using table 0 to represent an invalid or not found table. Table 0 is a legit table in linux (although it is reserved for unicast addressing). I think it would be better to make a constant called "noTable" or something and use -1.

2025-01-07 09:55 UTC, jcaamano commented on go-controller/pkg/libovsdb/ops/router.go
> +func GetRouterLogicalRouterStaticRoutesWithPredicate(nbClient libovsdbclient.Client, router *nbdb.LogicalRouter, p logicalRouterStaticRoutePredicate) ([]*nbdb.LogicalRouterStaticRoute, error) {
`FindLogicalRouterStaticRoutesWithPredicate` looks up the entire table. `GetRouterLogicalRouterStaticRoutesWithPredicate` looks up just among the routes of a specific router, which is what we want since we operate in the context of a specific network.

2025-01-07 09:57 UTC, jcaamano commented on go-controller/pkg/libovsdb/ops/router.go
> -		lrsr := lrsr
I can leave it but we aren't copying that pointer anywhere anymore so it is not needed.

2025-01-07 10:00 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	if c.networks[name] != nil {
Not possible. Check not needed.

This is remnant code from when the network ID was not being set by NetworkManager.

2025-01-07 10:52 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	setTimer := func(t *time.Timer, d time.Duration) *time.Timer {
hmm I didn't have those other controllers in mind when I did this. If I had to think about differences though:

- Not having a ticker running if we don't actually need one
- Be in control of the delay with which resubscribe which helps because I will have a full sync after that.

2025-01-07 10:55 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +					continue
If we are unsubscribed, the channel is closed and then we set the timer again.

2025-01-07 10:59 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +		t := setTimer(nil, subscribePeriod)
Technically not a leak per se, it's just that the timer is not garbage collected until it expires. This becomes a problem if you are spawning a lot of different timers with long timeouts or in shorts periods of time (using constructs as `time.After` or the like). Here we are just reusing the same timers all over again, so its only two.

Anyway, aside from the clarification, you are right.

2025-01-07 11:02 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	reconcile := info != nil && table != 0 && !current
Will do. Just thought that 0 is just as invalid as -1 for us since we are not operating with that table and makes things easier since I don't have to deal with initialization.

2025-01-07 11:09 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +	if c.networks[name] != nil {
I prefer to leave as is though, just in case there is problems elsewhere.

2025-01-07 23:24 UTC, trozet commented on go-controller/pkg/ovn/routeimport/route_import.go
> +					continue
the original controller we started with for subscribing to netlink was address manager:
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/node/node_ip_handler_linux.go#L173

I remember there were a bunch of problems with it and several fixes went in. The other controllers like link manager:
https://github.com/ovn-kubernetes/ovn-kubernetes/blob/master/go-controller/pkg/node/linkmanager/link_network_manager.go

rule manager, route manager all follow this pattern. Probably would have been better at some point to make it a netlinkController generic type that all these things could just share. Anyway the channel getting stuck thing...that may have been in an underlying library and I'm misremembering, but I do for sure remember a case where we were in a state where we did not resubscribe.

My main point here is I would just leverage the other patterns that already exist, and hopefully someone consolidates them all to a single shareable controller later. If you think the pattern that already exists is flawed or that somehow yours is better then we can potentially switch those later to use this pattern. I just dont want a bunch of different ways to do the same thing, especially when I think your code is watching links, and we already have a link manager.

2025-01-08 10:47 UTC, jcaamano commented on go-controller/pkg/ovn/routeimport/route_import.go
> +					continue
All those instances you mention are re-subscribing when the channel is closed, they are not working around any stuck channel issue really, in that respect they are doing the same thing that I am doing here.

So the difference is the use of a ticker vs the use of a timer, or in other words, when we a re-resubscribing: immediately when the subscription is lost, then again with a varying delay depending on ticker state; vs with a controlled delay always, respectively. I feel more comfortable with my approach but I will change to the other one .

VRF Manager is also watching links :stuck_out_tongue:

2025-01-08 11:30 UTC, jcaamano commented on go-controller/pkg/libovsdb/ops/router.go
> +func GetRouterLogicalRouterStaticRoutesWithPredicate(nbClient libovsdbclient.Client, router *nbdb.LogicalRouter, p logicalRouterStaticRoutePredicate) ([]*nbdb.LogicalRouterStaticRoute, error) {
I see.  I guess since the client doesn't give us the tools to guarantee this consistency we have to find other ways. The existing approach might be better but it is not really consistent either since the snapshot of the router is taken at a different point in time than that of the routes.

I think in general we achieve consistency by defining an owner of the data and hoping nobody else changes it. Which is what I am doing. It would be better done with ObjectIDs but I haven't had the time yet.

I am not really sure about the other use cases but I had already changed the use of `FindLogicalRouterStaticRoutesWithPredicate` that you pointed me to to `GetRouterLogicalRouterStaticRoutesWithPredicate`. But I am not sure that is what you mean since it is just a private use and you talk about `single common method`. Let me know.

2025-01-08 23:29 UTC, trozet approved these changes

2025-01-08 23:29 UTC, merged