kubevirt, l2, udpn: After live migration send CA to reconcile ipv6 default gw path.
ovn-kubernetes/ovn-kubernetes pull request #4847
Opened 2024-11-25 12:17 UTC by qinqon

## 📑 Description
At current layer2 topology each node has gateway router ipv6 link local ip and mac addresses, this end up with a multipath ipv6 defaujl gateways at VMs.

This change send a router advertisment with lifetime 0 to remove the ipv6 default gw path using the node where the VM was running before migration and send another one with lifetime max with the gw path where the VM is currently running after migration (after live migration the VM is not going to send a router solicitation so the router advertisment should be generated from ovn-k).

Fixes https://issues.redhat.com/browse/SDN-5424

## Additional Information for reviewers
Note that another fix that uses nftables to block RAs from external nodes is in progress, this PR should work in conjuntion with that.

Also note that proper solution is to use the future OVN transit router topology where the gw will have the same ip and mac addresses independently of the node where the VM is running.

## ✅ Checks

- [ ] My code requires changes to the documentation
- [ ] if so, I have updated the documentation as required
- [x] My code requires tests
- [ ] if so, I have added and/or updated the tests as required
- [ ] All the tests have passed in the CI

## How to verify it
The PR has e2e check to ipv6 default gw path after live migration.

2025-03-02 07:37 UTC, oshoval commented
/lifecycle stale cancel

2025-03-05 14:48 UTC, qinqon commented
Know flake: 
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936

2025-03-06 09:03 UTC, oshoval reviewed
Nice, thanks

2025-03-06 09:03 UTC, oshoval commented on test/e2e/kubevirt.go
> +						Should(Equal(expectedGatewayMAC), step)
please consider wrapping in some helper functions to make it shorter and ease readability

(same for the snippet below for isIPv6Supported)

2025-03-10 06:17 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
That was my first approach, but I needed more low level mechanism to "cook" the src ip and mac since we don't want to send the RA with the management port src/ip.

2025-03-10 06:33 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +	targetPodAnnotation, err := util.UnmarshalPodAnnotation(liveMigration.TargetPod.Annotations, netInfo.GetNADs()[0])
Hummm, maybe  you right let me investigate the scenario where we have a primary UDN shared between namesapces, at the end he controller is per network not per NAD, and when primary UDN is shared between namespaces we have different NAD with the same network so...

2025-03-10 06:41 UTC, qinqon commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	if hasIPv6Subnet, _ := oc.IPMode(); hasIPv6Subnet {
We don't support layer2 topology for non IC, does not make sense to add a check here, if a lot of "checks" are already missing.

Also at non IC these RAs do not hurt.

2025-03-10 06:42 UTC, qinqon commented on test/e2e/kubevirt.go
> +						Should(Equal(expectedGatewayMAC), step)
I don't see this code being called more than once.

2025-03-11 11:43 UTC, oshoval commented
Thanks, lgtm (limited of course to what i know)

2025-03-12 07:20 UTC, qinqon commented
After latest change to remove `GetNADs[0]` CI is unstable, the fix was looking for the active netinfo at the namespace and use it for GARP and unsolicited RAs

2025-03-12 08:00 UTC, oshoval commented
but isn't `targetPodAnnotation, err := util.UnmarshalPodAnnotation(liveMigration.TargetPod.Annotations, netInfo.GetNADs()[0])` problematic as well to keep ?
maybe need to iterate on them manually and find the required one ?

2025-03-12 08:57 UTC, qinqon commented
> but isn't `targetPodAnnotation, err := util.UnmarshalPodAnnotation(liveMigration.TargetPod.Annotations, netInfo.GetNADs()[0])` problematic as well to keep ? maybe need to iterate on them manually and find the required one ?

It's something else, I am manually generating RAs with lifetime 0 and looks like they don't remove the routes

2025-03-13 05:25 UTC, qinqon commented
> Thanks, so netInfo.GetNADs()[0]) should be changed to the fix ?

We needed the NAD to retrieve the mac address, but I think we can just broadcast the RA so no need for nad, it will simplify the code.

2025-03-13 09:15 UTC, maiqueb commented
I wonder about this explanation (maybe I'm missing something ...):
> so the issue is that fedora35 is quite old and don't fully implement IPv6 standard ignoring RA's lifetime=0

How did it pass before ?... Were you using a different image ?

2025-03-13 10:12 UTC, maiqueb requested changes
Really nice PR. 

I've caught something which I think is wrong (bad copy paste) and have a bunch of opinionated suggestions. 

Let me hear your thoughts !

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt.go
> +					Expect(err).ToNot(HaveOccurred())
nit: 
```suggestion
					Expect(err).NotTo(HaveOccurred())
```

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt.go
> +					sourceNodeIPv6GatewayPath, err := kubevirt.GenerateGatwayIPv6RouterLLA(sourceNode, netConfig.networkName)
```suggestion
					sourceNodeIPv6GatewayPath, err := kubevirt.GenerateGatewayIPv6RouterLLA(sourceNode, netConfig.networkName)
```

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt/net.go
> +func GenerateGatwayIPv6RouterLLA(node *corev1.Node, networkName string) (string, error) {
```suggestion
func GenerateGatewayIPv6RouterLLA(node *corev1.Node, networkName string) (string, error) {
```

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt/net.go
> +	return util.HWAddrToIPv6LLA(util.IPAddrToHWAddr(lrpAddresses[0].IP)).String(), nil
IMHO you need to assert the nodes have join addresses. Either in the caller, or here, within the helper.

And please remind me: the join IP addresses will **always** be the first entry in the list, right ?

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt/net.go
> +func RetrieveIPv6GatwayPaths(vmi *v1.VirtualMachineInstance) ([]string, error) {
```suggestion
func RetrieveIPv6GatewayPaths(vmi *v1.VirtualMachineInstance) ([]string, error) {
```

2025-03-13 10:12 UTC, maiqueb commented on test/e2e/kubevirt/net.go
> +func RetrieveIPv6GatwayPaths(vmi *v1.VirtualMachineInstance) ([]string, error) {
And actually, what do you think about naming this `RetrieveIPv6Gateways` ? The `path` suffix confuses me.

2025-03-13 11:53 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +		}
I prefer to have it here with the nice struct field names and all, no need for indirections if we are using this only once.

2025-03-13 11:56 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +func ReconcileIPv6DefaultGatewayAfterLiveMigration(watchFactory *factory.WatchFactory, netInfo util.NetInfo, liveMigration *LiveMigrationStatus, interfaceName string) error {
This is going to be gone after transit router change, let's just do a free function here, so it's easier to remove later on.

2025-03-13 12:09 UTC, maiqueb commented on go-controller/pkg/kubevirt/pod.go
> +func ReconcileIPv6DefaultGatewayAfterLiveMigration(watchFactory *factory.WatchFactory, netInfo util.NetInfo, liveMigration *LiveMigrationStatus, interfaceName string) error {
Yeah, but we have literally no idea on when that's landing. I'm not saying this is a must, I'm just saying "we'll change this in the future" is not an amazing argument. Everything's subject to change.

2025-03-13 13:39 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +func ReconcileIPv6DefaultGatewayAfterLiveMigration(watchFactory *factory.WatchFactory, netInfo util.NetInfo, liveMigration *LiveMigrationStatus, interfaceName string) error {
Hummm, ok let me do the struct with the ipv4 and ipv6 functions (at the end it looks good).

2025-03-13 13:54 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +	ra.SourceIP = util.HWAddrToIPv6LLA(ra.SourceMAC)
fair enough

2025-03-13 13:57 UTC, qinqon commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	if hasIPv6Subnet, _ := oc.IPMode(); hasIPv6Subnet {
wow good catch thanks !

2025-03-13 14:07 UTC, qinqon commented on test/e2e/kubevirt/net.go
> +	return util.HWAddrToIPv6LLA(util.IPAddrToHWAddr(lrpAddresses[0].IP)).String(), nil
> IMHO you need to assert the nodes have join addresses. Either in the caller, or here, within the helper.

ok. 


And please remind me: the join IP addresses will **always** be the first entry in the list, right ?

This is the node annotation for join addreses it just has join addreses this is not the LRP network addreses.

2025-03-13 18:43 UTC, maiqueb commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	defaultGatewayReconciler *kubevirt.DefaultGatewayReconciler
nit: maybe defaultGateway is a bit redundant ? Isn't gateway enough ?

2025-03-13 18:47 UTC, maiqueb submitted a review, later dismissed
Thank you !

2025-03-14 08:35 UTC, qinqon commented
known flake:
- https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4936

2025-03-14 09:34 UTC, kyrtapz reviewed
Thanks @qinqon!
I really appreciate the commit breakdown :)

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/util/ndp/ra.go
> +		defaultRoutePreferenceFlag := uint8(0x08)
From the RFC:
https://datatracker.ietf.org/doc/html/rfc4191#section-2.2
```
   Prf (Default Router Preference)
            2-bit signed integer.  Indicates whether to prefer this
            router over other default routers.  If the Router Lifetime
            is zero, the preference value MUST be set to (00) by the
            sender and MUST be ignored by the receiver.  If the Reserved
            (10) value is received, the receiver MUST treat the value as
            if it were (00).
```

So we are sending incorrect route preference flags for the RAs with 0 lifetime.

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/util/ndp/ra.go
> +			return err
Would it be possible for us to Serialize all packets first and send them all after that?
If a failure occurs in consecutive RAs and we exit the function, we might clean up routes without sending the subsequent ones.

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/util/ndp/ra.go
> +		managedAddressFlag := uint8(0x80)
Please add a comment explaining the used flags.

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/kubevirt/pod.go
> +func (r *DefaultGatewayReconciler) ReconcileIPv6AfterLiveMigration(liveMigration *LiveMigrationStatus) error {
I think this would be a good place to provide a comment around the approach you took to clean up the extra routes. Basically explaining what and why we send the RAs after migration.

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/kubevirt/pod.go
> +func newRouterAdvertisementFromJoinIPAndLifetime(ip net.IP, lifetime uint16) ndp.RouterAdvertisment {
Could you please add a docblock to this function explaining the purpose of using multicast?
I know the function is private but I am sure I will forget the details tomorrow :dizzy:

2025-03-14 09:34 UTC, kyrtapz commented on go-controller/pkg/kubevirt/types.go
> +type DefaultGatewayReconciler struct {
NIT: missing docblock

2025-03-14 09:34 UTC, kyrtapz commented on test/e2e/kubevirt.go
> +				if isIPv6Supported() {
Question: Do we run this test in CI on dualstack?

2025-03-14 09:34 UTC, kyrtapz commented on test/e2e/kubevirt.go
> +					obtainedIPv6Gateways, err := kubevirt.RetrieveIPv6Gateways(vmi)
Should we also verify the count of V6 gateways?

2025-03-14 09:34 UTC, kyrtapz commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
Please add an explanation for moving to F39 in the commit message.
Is there any bug tracking the RA with lifetime 0 issue in Fedora? That would be useful as well.

2025-03-14 09:43 UTC, maiqueb commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
I mean ... we were running fc35 - which is not supported since 2022-12-13 per the [fedora docs](https://docs.fedoraproject.org/en-US/releases/eol/).

Actually, even fc39 is currently unsupported. Couldn't we use 40 instead ?

2025-03-14 09:52 UTC, qinqon commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
> I mean ... we were running fc35 - which is not supported since 2022-12-13 per the [fedora docs](https://docs.fedoraproject.org/en-US/releases/eol/).
> 
> Actually, even fc39 is currently unsupported. Couldn't we use 40 instead ?

If we use fedora40 then we need either https://github.com/kubevirt/kubevirt/pull/13458 (not present at v1.4.0 kubevirt) or disable the NetworkManager acd mechanism

2025-03-14 09:53 UTC, kyrtapz commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
> I mean ... we were running fc35 - which is not supported since 2022-12-13 per the [fedora docs](https://docs.fedoraproject.org/en-US/releases/eol/).

Sure that's a valid reason, would be good to have it in the commit message.
I don't think that was the case here though? It would be great to have a tracker for the issue @qinqon mentioned.

2025-03-14 09:54 UTC, qinqon commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
> > I mean ... we were running fc35 - which is not supported since 2022-12-13 per the [fedora docs](https://docs.fedoraproject.org/en-US/releases/eol/).
> 
> Sure that's a valid reason, would be good to have it in the commit message. I don't think that was the case here though? It would be great to have a tracker for the issue @qinqon mentioned.

Also I was thinking that would be good to backport https://github.com/kubevirt/kubevirt/pull/13458 to openshift virt 4.18 since this is more or less GA for primary UDNs ?

2025-03-14 10:07 UTC, qinqon commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
Ahh we have kubevirt/kubevirt 1.5.0 hours ago, that should contain the ignore arp fix, let me try fedora 40, but still we need to backport the fix to 1.4 so it lands on openshift virt 4.18

2025-03-14 10:20 UTC, qinqon commented on test/e2e/kubevirt/types.go
> +	FedoraContainerDiskImage                = "quay.io/containerdisks/fedora:39"
> > I mean ... we were running fc35 - which is not supported since 2022-12-13 per the [fedora docs](https://docs.fedoraproject.org/en-US/releases/eol/).
> 
> Sure that's a valid reason, would be good to have it in the commit message. I don't think that was the case here though? It would be great to have a tracker for the issue @qinqon mentioned.

@kyrtapz I don't find the bug since it's quite old stuff, is this mandatory ?

2025-03-14 10:30 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +		defaultRoutePreferenceFlag := uint8(0x08)
Good catch! thanks

2025-03-14 10:40 UTC, maiqueb commented on go-controller/pkg/util/ndp/ra.go
> +		defaultRoutePreferenceFlag := uint8(0x08)
actually, could this be the reason why it doesn't work on fc35 ? Just wondering, I got no proof.

2025-03-14 10:43 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +			return err
Make sense, this has to be as much as possible all or nothing.

2025-03-14 10:52 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +type RouterAdvertisment struct {
I am not using that library for this, since I need some more low level stuff, so do not make sense to use it just for their structs, also that would be an implementation details that we want to hide, like for example now we can change the library we use to implement this without affecting the caller code.

2025-03-14 11:14 UTC, qinqon commented on test/e2e/kubevirt.go
> +				if isIPv6Supported() {
Yep, kubevirt interconnect CI job is dual stack

2025-03-14 11:17 UTC, qinqon commented on test/e2e/kubevirt.go
> +					obtainedIPv6Gateways, err := kubevirt.RetrieveIPv6Gateways(vmi)
Didn't want to do it since that would change after merging 
https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4852
we just care for old node gateway path gone and new node gateway path configured.

2025-03-14 13:00 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +		defaultRoutePreferenceFlag := uint8(0x08)
Humm good point, let me check.

2025-03-19 08:09 UTC, kyrtapz commented on go-controller/pkg/util/ndp/ra.go
> +type RouterAdvertisment struct {
I am ok with keeping it as is if that is what you prefer but could you add doc lines for fields explaining their use? Especially because some of those are not attributes of the route advertisement.

2025-03-24 07:36 UTC, tssurya commented
/assign @tssurya

2025-04-11 12:12 UTC, tssurya commented on go-controller/pkg/kubevirt/pod.go
> +		DestinationMAC: net.HardwareAddr{0x33, 0x33, 0, 0, 0, 0x1},
to whom does this hardcoded MAC belong to ? can you add a comment here for that

2025-04-11 12:14 UTC, tssurya commented on go-controller/pkg/kubevirt/pod.go
> +		SourceIP:       util.HWAddrToIPv6LLA(sourceMAC),
so this is the LLA IP of the GR's? not the joinIP?

2025-04-11 12:15 UTC, tssurya commented on go-controller/pkg/kubevirt/types.go
> +type DefaultGatewayReconciler struct {
nit: hmm why is this in types.go file? the functions are living in pod.go? can we just co-locate them?
types.go from what I can tell is just constants?

2025-04-11 12:17 UTC, tssurya commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +			return err
can we wrap these into custom errors that can be easily spotted for debugging purposes?

2025-04-11 12:18 UTC, tssurya commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +		oc.defaultGatewayReconciler = kubevirt.NewDefaultGatewayReconciler(oc.watchFactory, oc.GetNetInfo(), util.GetNetworkScopedK8sMgmtHostIntfName(uint(oc.GetNetworkID())))
so this reconciler is always created but only used from live migration path so application only to live migrated vms right?

2025-04-11 12:20 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
let's add this info into the PR describe on why we didn't pick existing golang ndp wrapper pkg and did our own?
I am not sure I follow the management port src/ip aspect you are mentioning

2025-04-11 12:24 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +		return err
will this error include the interfaceName?

2025-04-11 12:26 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +		return err
change it to 
return fmt.Errorf("failed to create raw socket for RA: %w", err) ?

2025-04-11 12:32 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +	defer c.Close()
shouldn't the defer be as close as possible to the create, or is it guaranteed sock is always nil if err is not nil?

2025-04-11 12:33 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +// and IP are not the ones on the LRP.
logical router policy?
no
logical router port?
yes

2025-04-11 12:34 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +	serializedRAs := [][]byte{}
this logic and below - was it inspired from the ndp library? I dunno enough to  check its correctness

2025-04-11 12:36 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +		//		router over other default routers.  If the Router Lifetime
thanks for the comments ++

2025-04-11 12:37 UTC, tssurya commented on go-controller/pkg/kubevirt/pod.go
> +	return ndp.SendRouterAdvertisements(r.interfaceName, ras...)
I see some scope for unit testing some of these bits but I won't hold the PR for that given you do have e2e's

2025-04-11 12:42 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +	for _, serializedRA := range serializedRAs {
This file I heavily trust your skills haha
I wish we had a library help for sending out these RAs but ..

2025-04-11 12:43 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +// SendRouterAdvertisements will send variadic RAs.
can you please add more than this as in it will open a new socket on the interface we pass and send the RAs :D

2025-04-11 12:45 UTC, tssurya commented on test/e2e/kubevirt.go
> +						Should(Equal([]string{targetNodeIPv6GatewayPath}), "should reconcile ipv6 gateway nexthop after live migration")
thanks so this is the check that makes sure we only have 1 lifetime=max RA from the local node correct?

2025-04-11 13:08 UTC, qinqon commented on go-controller/go.mod
> +	github.com/mdlayher/socket v0.2.1
To be able to "cook" RAs, meaning sending RAs with changed src ip/mac we need raw sockets, this library is a raw sockets implementation from the same author.

2025-04-11 13:22 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +		// the VM's will still have the old default gw paths, so we need to remove it
After the upgrade from these changes, sending to all the nodes is not really needed, but don't know if it's worth it to discover if we really need to send to all of them or not.

2025-04-14 06:16 UTC, tssurya commented on go-controller/go.mod
> +	github.com/mdlayher/socket v0.2.1
no I meant why did it jump positions?

2025-04-14 06:17 UTC, tssurya commented on go-controller/pkg/kubevirt/pod.go
> +		// the VM's will still have the old default gw paths, so we need to remove it
so I think if you update your comment with that info its better because currently the comment states this is a must needed thing to be done

2025-04-14 06:38 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +			return err
wrapping and using NewSuppressError to skip event, but we cannot skip the IsNotSet error since this has to be retried.

2025-04-14 06:53 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +	targetNode, err := r.watchFactory.GetNode(liveMigration.TargetPod.Spec.NodeName)
I prefer to fetch it again so if the target node we can easily throw and error, if we do this stuff in the loop then we have to check if we did found it after the loop, also I don't think adding the target node logic into the loop is a big performance gain.

2025-04-14 07:02 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +// This is done by sending a pair of unsolicited RA's one with lifetime=0
Fixing, this is from previous version where we were jus sending RA with lifetime=0 at the live migration source node

2025-04-14 07:24 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +		return nil
When target domain is ready, the target pod is annotation with a special kubevirt annotation, this will trigger reconcile and this code will be execute again.

2025-04-14 07:27 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +	return ndp.SendRouterAdvertisements(r.interfaceName, ras...)
Right, my though is that for this "temporal" code e2e is enough.

2025-04-14 08:54 UTC, maiqueb commented on go-controller/go.mod
> +	github.com/mdlayher/socket v0.2.1
Previously it was a dependency of some package we were importing, and now we're directly using it. Hence it got moved from "indirect" dependency, to a "direct" dependency.

2025-04-14 09:03 UTC, maiqueb commented on go-controller/pkg/kubevirt/pod.go
> +	for _, node := range nodes {
while I don't see anything wrong w/ this approach, I think the code would be more readable if it looked something like (using some sort of pseudo-code):
```golang
targetNode := migrationTargetNode(liveMigration)
nonTargetNodes := nonTargetNodes(liveMigration)

ras := []ndp.RouterAdvertisement{configNewGateway(targetNode), forgetOldGateways(nonTargetNodes)...}
...
```

Or something along those lines. This is highly opinionated, feel free to disregard.

2025-04-14 09:31 UTC, tssurya commented on go-controller/pkg/kubevirt/pod.go
> +		return nil
ack

2025-04-14 09:47 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +// other VM's receive this it's ok, since it match with the network configuration
> I don't understand this last bit
> 
> so what you mean is actually we only want to send these for the VM being migrated but ofc all hosts on the network will receive this RA and that is still OK? this is making me think the following:
> 

As far as I remember on IC the RAs where not traversing the zones, so only the VMs running at the node will receive the unsolicited RA.

> * Imagine I have podA(vmA) on nodeA and podB(vmB) on nodeB
> * I live migrated both pods so now podA(vmA) shows up on nodeB and podB(vmB) shows up on nodeA
> * As a result here when the GRA sends out the RA with lifetime=0 won't it hurt the podB which shouldn't be receiving this but it will?

podB are not going to receive the RAs with lifetime=0 that should not since RAs are not traversing the zones.

2025-04-14 09:48 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +		SourceIP:       util.HWAddrToIPv6LLA(sourceMAC),
Yep, as by the IPv6 RFCs the RA's should use the LLAs as src ip instead of global IPs.

2025-04-14 09:50 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +		DestinationMAC: net.HardwareAddr{0x33, 0x33, 0, 0, 0, 0x1},
I will add a comment about ipv6 mac multicast address

2025-04-14 10:01 UTC, qinqon commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +		oc.defaultGatewayReconciler = kubevirt.NewDefaultGatewayReconciler(oc.watchFactory, oc.GetNetInfo(), util.GetNetworkScopedK8sMgmtHostIntfName(uint(oc.GetNetworkID())))
Yep, we are guarding it later on with `IsPodAllowedForMigration`

2025-04-14 10:09 UTC, qinqon commented on go-controller/go.mod
> +	github.com/mdlayher/socket v0.2.1
Yep, that's it, now the dependency is not transitive so it pops up at "direct" one.

2025-04-14 10:13 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> let's add this info into the PR describe on why we didn't pick existing golang ndp wrapper pkg and did our own?  

I will add a note the PR description, just as a note we didn't create our own, we used the ones from `github.com/google/gopacket` (already included on the project) that allow us to do this kind of things.

> I am not sure I follow the management port src/ip aspect you are mentioning

with the `mdlayher/ndp` the src(ip, mac) from the RA is the one from the interface we are sending the message from, in our case the mgmt one, but instead we need them to be the gateway routers join IP LLA/MAC (this is how the VM's recognice what route path are we talking about).

2025-04-14 10:19 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +// and IP are not the ones on the LRP.
rewording, sinc eit does not make any sense.

2025-04-14 10:25 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +	defer c.Close()
From what I see in example from the socket project they close after handling error, so I suppose this is fine 

https://github.com/mdlayher/socket/blob/main/internal/sockettest/sockettest.go#L32

2025-04-14 10:27 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +	serializedRAs := [][]byte{}
So I came up with thise using the ipv6toolkit to generate the unsolicited RAs that make the default gw multipath be reconciled, then used tcpdump to inspect them, then replicate whatever is needed with this library comparing tcpdumps.

The only validation we have that is ok is the e2e, ipv6 default gw is reconciled so we good.

2025-04-14 10:27 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +	for _, serializedRA := range serializedRAs {
well now we have.

2025-04-14 10:29 UTC, qinqon commented
Addressing @tssurya comments at [force-push](https://github.com/ovn-kubernetes/ovn-kubernetes/compare/17ab8ba5a4b517d2db7f6935277160bbe730125d..572278b3e237c9ce04592a07e8abd50562a96b74)

2025-04-14 10:35 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +// other VM's receive this it's ok, since it match with the network configuration
I want to verify again that this unsolicited RAs are not traversing IC

2025-04-14 10:37 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +// other VM's receive this it's ok, since it match with the network configuration
@tssurya good catch, I will narrow down dst ip/mac to VM's one.

We are suppose to block them at other zones with the nftables and all, but during upgrades who knows what will happend let's limit it.

2025-04-14 11:38 UTC, tssurya commented on go-controller/go.mod
> +	github.com/mdlayher/socket v0.2.1
ahh sorry didn't notice that, thanks

2025-04-14 11:48 UTC, tssurya commented on go-controller/pkg/util/ndp/ra.go
> +		//		router over other default routers.  If the Router Lifetime
hmm why did you remove this on the latest push?

2025-04-14 12:31 UTC, qinqon commented
Last [force-push](https://github.com/ovn-kubernetes/ovn-kubernetes/compare/572278b3e237c9ce04592a07e8abd50562a96b74..f6cef3296a3d376e7f5bf0e970f8a9a3582737cc):
- Fix lint issues
- Send RAs only to the VM instead of multicast

2025-04-14 12:32 UTC, qinqon commented on go-controller/pkg/kubevirt/pod.go
> +	for _, node := range nodes {
Don't know if it's worth it for temporal code like this.

2025-04-14 15:46 UTC, qinqon commented
@tssurya this is ready for re review

2025-04-14 15:47 UTC, qinqon commented on go-controller/pkg/util/ndp/ra.go
> +		//		router over other default routers.  If the Router Lifetime
humm did I ? damn it

2025-04-15 16:20 UTC, tssurya approved these changes
lgtm
thank you @qinqon for the changes this is ready for merge my comments were addressed except https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4847/files#r2041530592 but that's fine its a nit
the other nit is you suppressed too much on the error from annotation parsing - what i mean was "annotation not found" suppression but again its a nit doesn't matter you can do a FUP if you push another PR
Once CI is green will merge this one

2025-04-15 16:38 UTC, tssurya commented
All 3 lanes that flaked in CI are known issues

1. https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/14472019313/job/40590614857?pr=4847 is https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4474
2. https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/14472019313/job/40590614820?pr=4847 is https://github.com/ovn-kubernetes/ovn-kubernetes/issues/4220
3. https://github.com/ovn-kubernetes/ovn-kubernetes/actions/runs/14472019313/job/40590614816?pr=4847 is related to https://github.com/actions/runner-images/issues/11985

2025-04-15 16:59 UTC, merged