Add BGP support for UDN
ovn-kubernetes/ovn-kubernetes pull request #4929
Opened 2024-12-18 14:25 UTC by arghosh93

## 📑 Description
This commit adds capability to advertise an user defined L3
    primary network over providers network. This commit takes care
    of implementation required while using either shared gateway
    mode or local gateway mode.
    This commit introduces various Reconcile function for different
    controllers so that node and ovn resources gets reconciled upon
    advertising an user defined network.
    As part of those Reconcile functions, following resources gets
    added or removed to allow traffic from outside network when the
    network is advertised:
    - OpenFlow flows. For shared gateway mode, one priority 16 flow
    gets added to forward traffic to patch port. For local gateway mode,
    one priority 15 flow gets added to forward traffic to LOCAL port.
    - SNAT rule from ovn_cluster_router specific to and UDN gets removed
    when that network gets advertised.
    - iptables return rule matching destination same as UDN subnet gets
    added to OVN-KUBE-UDN-MASQUERADE chain when the network is advertised
    and gateway mode is local.
    - IP rule gets modified to match UDN subnet instead of the UDN
    specific masquerade subnet.
    - One IP route gets added to the UDN specific vrf table when gateway
    mode is local. This is to route traffic coming for UDN network and to
    forward to UDN specific management port.

Fixes #

## Additional Information for reviewers

## ✅ Checks

- [ ] My code requires changes to the documentation
- [ ] if so, I have updated the documentation as required
- [ ] My code requires tests
- [ ] if so, I have added and/or updated the tests as required
- [ ] All the tests have passed in the CI 

## How to verify it

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/secondary_node_network_controller.go
>  }
I would move these two methods to `UserDefinedNetworkGateway` as it is responsible for what it is being done (and undone) here.

I would also have them under a general `UserDefinedNetworkGateway.Reconcile` method just as we have `UserDefinedNetworkGateway.gateway.Reconcile` which you can reuse from the former to sync flows, and you can also reuse `UserDefinedNetworkGateway.gateway.Reconcile`

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +				if (isPodNetworkAdvertised || isUDNNetworkAdvertised) && config.Gateway.Mode == config.GatewayModeLocal {
How do you know to which network does the `isUDNNetworkAdvertised` apply to? Have you tested with multiple UDNs where only a subset of them is advertised? It looks like just as `bridge.netConfig` is a map with different networks, we should also have a map to store `isUDNNetworkAdvertised` per network. I guess we can use `bridge.netConfig` as well for this.

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/secondary_node_network_controller.go
> +	subnets, err := util.ParseNodeHostSubnetAnnotation(node, types.DefaultNetworkName)
I guess we can avoid passing this subnets if they are already provided through the `bridgeConfiguration`

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +						nodeSubnets, err = util.ParseNodeHostSubnetAnnotation(node, netName)
This parsing is very expensive and we will parse the annotation fully for each of all the networks each time a network config changes. 

We better do it just once so it should probably be set on `bridge.netConfig` from `UserDefinedNetworkGateway`

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/secondary_node_network_controller.go
> +	udnReplyIPRules, err := oc.gateway.constructUDNVRFIPRules(vrfTableId)
Will these replace the old rules os will there be leftovers?

2024-12-30 17:50 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +// 2000:	from all to 10.132.0.0/14 lookup 1009
`add` is confusing here. It can be understood as added to the rules above. I would explain it better.

2025-01-08 15:33 UTC, arghosh93 commented on go-controller/pkg/ovn/base_network_controller.go
>  }
As per discussion DefaultNetworkController.Reconcile and SecondaryLayer3NetworkController.Reconcile both calls BaseNetworkController.reconcile to complete the reconciliation.

2025-01-08 15:34 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
>  	return hostSubnets, nil
Ack

2025-01-08 15:34 UTC, arghosh93 commented on go-controller/pkg/node/vrfmanager/vrf_manager.go
> +func (vrfm *Controller) DeleteVRFRoutes(name string, routes []netlink.Route) error {
Removed it. Will push new changes soon.

2025-01-08 15:35 UTC, arghosh93 commented on go-controller/pkg/node/secondary_node_network_controller.go
> +}
Yaa, I agree. I have tested without this RETURN rule and it works as expected.

2025-01-08 15:35 UTC, arghosh93 commented on go-controller/pkg/node/secondary_node_network_controller.go
>  }
Ack

2025-01-08 15:36 UTC, arghosh93 commented on go-controller/pkg/node/gateway_shared_intf.go
> +				if (isPodNetworkAdvertised || isUDNNetworkAdvertised) && config.Gateway.Mode == config.GatewayModeLocal {
yes, makes sense. I have made required changes. Will push soon.

2025-01-08 15:38 UTC, arghosh93 commented on go-controller/pkg/node/secondary_node_network_controller.go
> +	udnReplyIPRules, err := oc.gateway.constructUDNVRFIPRules(vrfTableId)
It will replace old IP rules.

2025-01-08 15:40 UTC, arghosh93 commented on go-controller/pkg/node/gateway_udn.go
> +// 2000:	from all to 10.132.0.0/14 lookup 1009
Ack

2025-01-09 13:31 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
Why don't you use `gatewaysFailed`? Then you don't have to pass in `retryNodes` and then the whole reconcile implementation si the same for all network types?

2025-01-09 13:33 UTC, jcaamano commented on go-controller/pkg/ovn/base_network_controller.go
> +			return err
Technically we should just klog an error here, since `ReconcileNetInfo` above is a point of no return (I had a comment on the original code, perhaps you can add it back) as once it is called. `NeedsReconciliation` will return `false` anyway.

2025-01-09 13:38 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	return nil
You should `return util.ReconcileNetInfo(oc.ReconcilableNetInfo, netInfo)`

2025-01-09 13:38 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_localnet_network_controller.go
> +	return nil
You should `return util.ReconcileNetInfo(oc.ReconcilableNetInfo, netInfo)`

2025-01-09 13:40 UTC, jcaamano commented on go-controller/pkg/node/secondary_node_network_controller.go
> +				return err
Technically we should just klog an error here, since ReconcileNetInfo above is a point of no return (I had a comment on the original code, perhaps you can add it back) as once it is called. NeedsReconciliation will return false anyway.

2025-01-09 13:44 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +			nodeSubnet: nodeSubnets,
nit: s/nodeSubnet/nodeSubnets

2025-01-09 13:46 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +// If isPodNetworkAdvertised is set to true then we update IP rules as below
nit: maybe s/update/replace ?

2025-01-09 13:55 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +// If isPodNetworkAdvertised is set to true then we update IP rules as below
Are you sure it is actually replacing the rules?

2025-01-09 13:57 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +		}
You shouldn't be handling the default network here

2025-01-09 13:59 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +	}
We should not need to pass the subnets if they are already stored in `openflowManager.defaultBridge.netConfig`

2025-01-09 14:08 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +		}
I think that the correct approach is add the new rules first, and then delete the old ones. We don't want a moment in time when there is just no rules.

2025-01-09 14:10 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +// If isPodNetworkAdvertised is set to true then we update IP rules as below
Ok, I see that you are deleting in `updateUDNVRFIPRule`.

So I would jsut preface the previous example with 
`If the network is not advertise, we set rules...`

And this example with
`If the network is advertised we set rules...`

2025-01-09 14:15 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +	isUDNNetworkAdvertisedLock sync.Mutex
I don't think you need this, the information is already available in `util.NetInfo` above.

2025-01-09 14:17 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) SetUDNNetworkAdvertised(networkName string, isUDNNetworkAdvertised bool) {
I don't think you need this method. Just do this on `Reconcile`. You will have the information updated iin NetInfo.

2025-01-09 14:19 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
> +		}
This is a map that can be accessed by Key, why are you iterating?

2025-01-09 14:19 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +		for netName, netConfig := range udng.openflowManager.defaultBridge.netConfig {
This is a map that can be accessed by Key, why are you iterating?

2025-01-09 14:44 UTC, jcaamano commented on go-controller/pkg/node/openflow_manager.go
> +	dftCommonFlows, err := commonFlows(subnets, c.defaultBridge, isPodNetworkAdvertised, isUDNNetworkAdvertised)
We don't need to be passing `isPodNetworkAdvertised, isUDNNetworkAdvertised` around anymore, all that information is now readily available in `openflowManager.defaultBridge.netConfig[<network name>]`

2025-01-09 14:46 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +	isUDNNetworkAdvertised bool
nit: s/isUDNNetworkAdvertised/isNetworkAdvertised

2025-01-09 14:47 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
> +		subnets:    config.Default.ClusterSubnets,
Also isUDNNetworkAdvertised

2025-01-09 14:49 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +				gw.isPodNetworkAdvertised, false); err != nil {
So it make sense to remove `gw.isPodNetworkAdvertised` from here and pass it instead in `gatewayInitInternal.bridgeForInterface` instead to initialize the proper value for the `bridgeUDNConfiguration` there

2025-01-09 14:54 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +		if config.Gateway.DisableSNATMultipleGWs || isPodNetworkAdvertised || isUDNNetworkAdvertised {
We shouldn't use these `PodNetworkAdvertised`,`isUDNNetworkAdvertised` any more. That information comes now from `bridge.netConfig`. Yoyu shoudl just iterate that and based the config from information obtained there.

2025-01-09 14:56 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
>  	g.isPodNetworkAdvertised = isPodNetworkAdvertised
We can probably get rid of these fields and just use `g.openflowManager.defaultBridge.netConfig`

2025-01-09 14:57 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +	isUDNNetworkAdvertised bool
Also, we probably need this to be an atomic, since `isUDNNetworkAdvertised` can change at any time and you will get a race

2025-01-10 06:51 UTC, arghosh93 commented on go-controller/pkg/node/gateway.go
> +		}
yaa, its a mistake. Will rectify in next push.

2025-01-10 06:51 UTC, arghosh93 commented on go-controller/pkg/node/gateway_udn.go
> +		for netName, netConfig := range udng.openflowManager.defaultBridge.netConfig {
yaa, its a mistake. Will rectify in next push.

2025-01-14 11:29 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
I am moving both addition and deletion of SNAT rule from addNode to a section which gets executed when gwFailed is set. I hope I am not breaking anything existing.

2025-01-14 14:24 UTC, jcaamano commented on go-controller/pkg/node/secondary_node_network_controller.go
> +				return err
Yes, below the point of no return which is `ReconcileNetInfo` call.

2025-01-14 14:35 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
No, please don't do that. I just had the question and I can take an answer.

2025-01-14 14:46 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
alternatively you can pass a callback

```
return oc.BaseNetworkController.reconcile(
    netInfo,
    func(node string) {oc.addNodeFailed.Store(node, true)}
)
```

so on base network controller
```
func (oc *BaseNetworkController) reconcile(netInfo util.NetInfo, prepareNodeReconcile func(string)) error {
	var err error
	var retryNodes []*kapi.Node
	var retryNodeNames []string
	oc.localZoneNodes.Range(func(key, value any) bool {
	...
	...
	for _, node := range retryNodes {
	        prepareNodeReconcile(node)
		err = oc.retryNodes.AddRetryObjWithAddNoBackoff(node)
		if err != nil {
			klog.Errorf("Failed to retry node %s for network %s: %v", node.Name, oc.GetNetworkName(), err)
		}
	}
	if len(retryNodes) > 0 {
		oc.retryNodes.RequestRetryObjs()
	}

	return nil
}
```

2025-01-15 07:37 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
Very nice idea. still there would be multiple nodes which would need reconciliation.

2025-01-15 09:02 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		oc.addNodeFailed.Store(node.Name, true)
all the nodes are being reconciled in the code excerpt above

2025-01-21 20:37 UTC, jcaamano reviewed
minor comments

we need to find out why the network-segmentation lanes are failing.

2025-01-21 20:37 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) constructUDNVRFIPRulesMasqueradeIP(vrfTableId int) ([]netlink.Rule, error) {
I feel like this could be way cleaner. 

I suggest we merge `constructUDNVRFIPRules` and `constructUDNVRFIPRulesMasqueradeIP`  methods into one.

then have as needed
```
addIPRules = append(addIPRules, generateIPRuleForPacketMark(...
```
then as needed
```
masqIPRules := append(masqIPRules, generateIPRuleForMasqIP(..
subnetIPRules := append(subnetIPRules, generateIPRuleForUDNSubnet(...
```
and then at the end
```
switch {
case !isNetworkAdvertised:
    addIPRules = append(addIPRules, masqIPRules...)
    delIPRules = append(delIPRules, masqIPRules...)
default:
    addIPRules = append(addIPRules, subnetIPRules...)
    delIPRules = append(delIPRules, masqIPRules...)
}
```
I guess we decided to leave the masqIPRules around in any case. But I say for now lets remove them.

2025-01-21 20:37 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +	udnReplyIPRules, deleteIPRule, err := udng.constructUDNVRFIPRules(vrfTableId)
nit: 
s/udnReplyIPRules/addIPRules
s/deleteIPRule/deleteIPRules

2025-01-21 20:37 UTC, jcaamano commented on go-controller/pkg/node/openflow_manager.go
> +	watchFactory factory.NodeWatchFactory
I don't think we need the watchFactory for anything so you can just remove it

2025-01-21 20:37 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		}
better:
```
if util.IsNetworkSegmentationSupportEnabled() && oc.IsPrimaryNetwork() {
   if !util.IsPodNetworkAdvertisedAtNode(oc, node.Name) {
       ....
   } else {
       ....
   }
}
```

2025-01-29 17:39 UTC, jcaamano approved these changes

2025-01-29 17:40 UTC, jcaamano commented
holding for this week

2025-01-31 15:53 UTC, arghosh93 commented
multi-homing lane is failing after my recent rebase on master.
`Summarizing 1 Failure:
  [FAIL] Multi Homing multiple pods connected to the same OVN-K secondary network [It] eventually configures pods that were added to an already existing network before the nad`
This e2e job was added as part of a recent commit[1] and I also did a change[2] to mitigate conflict. I will check this next week.
[1] - https://github.com/ovn-kubernetes/ovn-kubernetes/commit/73208692d382a8568ee39030273cc8a08f2ef357
[2] - https://github.com/ovn-kubernetes/ovn-kubernetes/blob/0dec7a4502786dcaf6bfd829607e7d9be249c77a/go-controller/pkg/ovn/base_network_controller.go#L236-L240

2025-02-10 12:25 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	}
Why are you doing this?

2025-02-10 12:25 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_localnet_network_controller.go
> +	}
Why are you doing this?

2025-02-10 14:33 UTC, jcaamano submitted a review, later dismissed

2025-02-21 00:16 UTC, trozet requested changes
only like halfway done. Will finish on Monday

2025-02-21 00:16 UTC, trozet commented on go-controller/pkg/node/gateway_udn.go
> +	klog.Info("Reconciling UDN gateway with updates")
list which UDN? network name

2025-02-24 10:32 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
>  func (g *gateway) SetPodNetworkAdvertised(isPodNetworkAdvertised bool) {
Might be more confusing since this `gateway` only exports API to serve the default network, whereas `UserDefinedNetworkGateway` is the one that exports functionality for UDN networks.

2025-02-24 10:34 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
> +	isNetworkAdvertised := g.openflowManager.defaultBridge.netConfig[types.DefaultNetworkName].advertised.Load()
I would do `gateway.getPodNetworkAdvertised` (unexported). Anyway, note that this is hardcoded for the default network which is guaranteed to exist.

2025-02-24 10:57 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +			if !config.Gateway.DisableSNATMultipleGWs && !isNetworkAdvertised {
hmmm so if the trick of this is `netConfig is not default`, wouldn't that check have to be done as part of UDN changes? Are we saying `disableSNATMultipleGWs` does not apply to L3 non default networks?

2025-02-24 10:57 UTC, jcaamano commented on go-controller/pkg/node/gateway_shared_intf.go
> +			for _, clusterEntry := range netConfig.subnets {
It is the entire subnet, and I guess that is what we want if we were using the entire subnet for the default network as well.

2025-02-24 16:01 UTC, trozet commented on go-controller/pkg/node/gateway.go
>  func (g *gateway) SetPodNetworkAdvertised(isPodNetworkAdvertised bool) {
Can we still name it SetDefaultPodNetworkAdvertised? Perhaps also change "gateway" to be defaultGateway or something. The latter could be done in another PR. It's not obvious that gateway is only default network.

2025-02-24 16:13 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
> +			if !config.Gateway.DisableSNATMultipleGWs && !isNetworkAdvertised {
So disableSNATMultipleGWs was not originally intended to apply to UDN. It was for MEG to signal that if a pod has multiple external gateways, do not SNAT the egress traffic. That being said, I think it is good how it is evolving to cover the UDN case with BGP if pod ips are advertised. So I think disableSNATMultipleGWs *DOES* apply to UDN.

But like I said in my comment if netConfig is not default (so its UDN) && !isNetworkAdvertised && disableSNATMultipleGWs then we should not program the flows for direct pod ingress

2025-02-24 16:21 UTC, arghosh93 commented on go-controller/pkg/node/gateway_udn.go
> +	klog.Info("Reconciling UDN gateway with updates")
Ack

2025-02-24 16:57 UTC, trozet commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) doReconcile() error {
how come this reconcile was implemented asynchronously? It looks like the calls inside of it are not expensive or blocked for long periods of time. The side effect of this being async is on node start up, the syncall method for networks will not be blocked on the reconcile.

2025-02-24 16:57 UTC, trozet commented on go-controller/pkg/ovn/base_network_controller.go
> +		klog.Errorf("Failed to reconcile network information for network %s: %v", oc.GetNetworkName(), err)
should you still continue past this point? If so, why?

2025-02-24 16:57 UTC, trozet commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +			if err := oc.deleteUDNNodeSubnetEgressSNAT(hostSubnets, node); err != nil {
i guess you need this for update. The function is a little confusing cause it's called addNode, we should probably rename it to addOrUpdateNode

2025-02-24 17:25 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) doReconcile() error {
This is not used on startup. Everything that needs to happen on startup happens synchronously in `AddNetwork`.

2025-02-24 17:34 UTC, jcaamano commented on go-controller/pkg/node/gateway.go
>  func (g *gateway) SetPodNetworkAdvertised(isPodNetworkAdvertised bool) {
I am ok with `SetDefaultPodNetworkAdvertised`

2025-02-25 06:39 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +	}
This was discussed and resolved.

2025-02-25 06:40 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_localnet_network_controller.go
> +	}
This was discussed and resolved.

2025-02-25 11:35 UTC, arghosh93 commented on go-controller/pkg/node/gateway.go
> +	isNetworkAdvertised := g.openflowManager.defaultBridge.netConfig[types.DefaultNetworkName].advertised.Load()
does below function definition seems fair? I am naming it GetDefaultPodNetworkAdvertised to keep it consistent with SetDefaultPodNetworkAdvertised.
`func (g *gateway) GetDefaultPodNetworkAdvertised() bool {
	return g.openflowManager.defaultBridge.netConfig[types.DefaultNetworkName].advertised.Load()
}`

2025-02-25 12:01 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +			if err := oc.deleteUDNNodeSubnetEgressSNAT(hostSubnets, node); err != nil {
I have not yet change the function name to keep it consistent with all other network controller's(ex: DefaultNetworkController) addNode function name. Moreover addNode gets called by addUpdateLocalNodeEvent(). Should I still go ahead and rename the function name?

2025-02-25 14:55 UTC, trozet commented on go-controller/pkg/node/gateway_shared_intf.go
> +			if !config.Gateway.DisableSNATMultipleGWs && !isNetworkAdvertised {
yeah sorry my comment was wrong. We should *NOT* consider DisableSNATMultipleGWs for UDN right now

2025-02-25 14:58 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) doReconcile() error {
It would be

func (c *networkController) Start() -> c.syncAll -> err := c.syncNetwork(network.GetNetworkName()) -> err = err = c.ensureNetwork(want) -> err := networkController.Start() -> oc.gateway.AddNetwork()

2025-02-25 15:03 UTC, trozet commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +			if err := oc.deleteUDNNodeSubnetEgressSNAT(hostSubnets, node); err != nil {
you can just leave it for now. I'll refactor it later.

2025-02-26 14:46 UTC, jcaamano commented on go-controller/pkg/node/gateway_udn.go
> +func (udng *UserDefinedNetworkGateway) doReconcile() error {
Yeah, I think we should. In general terms Start should just get things started and have minimum surface for failure. However that requires not having dependencies to do things synchronously. Too much for this PR.

2025-02-26 18:05 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +		gwManager.netInfo = oc.GetNetInfo()
You don't need to do this. `gwManager.netInfo` is already `oc.GetNetInfo()` which is an interface/pointer that is never replaced. It's just updated internally.

2025-02-26 18:06 UTC, jcaamano commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		gwManager.netInfo = oc.GetNetInfo()
You don't need to do this. gwManager.netInfo is already oc.GetNetInfo() which is an interface/pointer that is never replaced. It's just updated internally.

2025-02-26 18:14 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer2_network_controller.go
> +		gwManager.netInfo = oc.GetNetInfo()
Ack

2025-02-26 18:23 UTC, arghosh93 commented on go-controller/pkg/ovn/secondary_layer3_network_controller.go
> +		gwManager.netInfo = oc.GetNetInfo()
Ack

2025-02-26 19:07 UTC, trozet approved these changes

2025-02-26 21:58 UTC, merged